common: &common
  adapter: postgresql

development:
  <<: *common
  database: ono_dev
  username: onomatopoeia
  password: password

test:
  <<: *common
  database: ono_test
  username: onomatopoeia
  password: password

# production:
#   <<: *common
#   database: ono_prod